export const WEATHER_FETCH_ENDED = 'WEATHER_FETCH_ENDED';
export const WEATHER_FETCH_STARTED = 'WEATHER_FETCH_STARTED';

export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const REMOVE_WEATHER_DATA = 'REMOVE_WEATHER_DATA';
